spring:
  datasource:
    url: jdbc:h2:file:./jwt-security
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect